courses/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('courses.views',
    url(r'^$', 'course_list'),
    url(r'^my/$', 'my_course_list'),
    url(r'^(?P<course_slug>\w+)/$', 'course_details'),
    url(r'^(?P<course_slug>\w+)/preferences/$', 'create_preferences'),
    url(r'^(?P<course_slug>\w+)/(?P<group_slug>\w+)/$', 'group_details'),
    url(r'^(?P<course_slug>\w+)/(?P<group_slug>\w+)/register$', 'register_user_to_group'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic.simple import direct_to_template
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wiwitasapps.views.home', name='home'),
    # url(r'^wiwitasapps/', include('wiwitasapps.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^courses/', include('courses.urls')),
    url(r'^accounts/', include('wiwitasprofile.urls')),
    url(r'^accounts/', include('registration.urls')),
)

courses/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

class Semester(models.Model):
    SEMESTER_CHOICES = (
        ('ws', _('winter semester')),
        ('ss', _('summer semester')),
    )
    
    type = models.CharField(max_length=2, choices=SEMESTER_CHOICES)
    year = models.IntegerField(help_text=_("for example: '2011'"))
    current = models.BooleanField()
    class Meta:
        unique_together = [('type','year')]
    
    def __unicode__(self):
        return u'%s %d' % (self.type.upper(), self.year)
    
    # override the save method s.t. it sets all other semester.current to false when saving a semester with current=true
    def save(self, *args, **kwargs):
        super(Semester, self).save(*args, **kwargs)
        if self.current:
            Semester.objects.exclude(id=self.id).update(current=False)


class Course(models.Model):
    name = models.CharField(max_length=100)
    slug=models.SlugField()
    description = models.TextField()
    admins = models.ManyToManyField(User)
    end_of_preference_phase = models.DateField()
    start_of_registration_phase = models.DateField()
    semester = models.ForeignKey(Semester)
    active = models.BooleanField()
    
    @property
    def capacity(self):
        aggregated = Group.objects.filter(course=self).aggregate(course_capacity=Sum('capacity'))
        return aggregated['course_capacity']
    
    @property
    def used_capacity(self):
        groups = Group.objects.filter(course=self)
        used_capacity = 0
        for group in groups:
            used_capacity += group.used_capacity
        return used_capacity
        
    
    def __unicode__(self):
        return self.name


class Group(models.Model):
    RHYTHM_CHOICES = (
        ('da', _('daily')),
        ('we', _('weekly')),
        ('bw', _('bi-weekly')),
        ('mo', _('monthly')),
        ('ot', _('one time')),
        ('ot', _('other')),
    )
    name = models.CharField(max_length=80)
    slug=models.SlugField()
    description = models.TextField()
    capacity = models.IntegerField()
    place = models.CharField(max_length=40)
    first_date = models.DateField()
    last_date = models.DateField()
    rhythm = models.CharField(max_length=2, choices=RHYTHM_CHOICES)
    starting_time = models.TimeField()
    ending_time = models.TimeField()
    course = models.ForeignKey(Course)
    admins = models.ManyToManyField(User, null=True, blank=True)
    
    @property
    def used_capacity(self):
        return Registration.objects.filter(group=self).count()
    
    def __unicode__(self):
        return u'%s, %s' % (self.course, self.name)
           

class Preference(models.Model):
    max_preferences = 5
    PREFERENCE_CHOICES = [(i, str(i)) for i in range(1, max_preferences+1)]
    
    user = models.ForeignKey(User)
    group = models.ForeignKey(Group)
    preference = models.IntegerField(choices=PREFERENCE_CHOICES)
    
    @property
    def group_capacity(self):
        return self.group.capacity
    
    def __unicode__(self):
        return u'%s, %s: %d' % (self.user, self.group, self.preference)


class Registration(models.Model):
    user = models.ForeignKey(User)
    group = models.ForeignKey(Group)
    
    class Meta:
        unique_together = [('user','group')]
    
    def __unicode__(self):
        return u'%s - %s' % (self.user, self.group)


class CourseOfStudies(models.Model):
    class Meta:
        verbose_name_plural = "Courses of Studies"

    course_of_studies = models.CharField(max_length=40)
    
    def __unicode__(self):
        return u'%s' % (self.course_of_studies)

courses/forms.py
from django import forms
from django.forms.formsets import BaseFormSet
from django.utils.translation import ugettext as _
        
class BasePreferenceFormSet(BaseFormSet):
    def clean(self):
        """Checks that each group is only selected once."""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        preferences = []
        for i in range(0, self.total_form_count()):
            form = self.forms[i]
            preference = form.cleaned_data['preference']
            if preference in preferences:
                raise forms.ValidationError(_("Each group can only be selected once."))
            preferences.append(preference)

courses/views.py
from django.views.generic import ListView
from courses.models import Course, Group, Semester, Preference
from courses.registration import Registrator
from courses.allocation import preference_administrator
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django import forms
from django.forms.formsets import formset_factory
from django.contrib import messages
from courses.forms import BasePreferenceFormSet


def course_list(request):
    site_headline = _("List of Courses")
    current_semester = Semester.objects.get(current=True)
    courses = Course.objects.filter(semester=current_semester)
    
    return render_to_response('courses/course_list.html', locals(), context_instance=RequestContext(request))

@login_required
def my_course_list(request):
    site_headline = _("My Courses")
    current_semester = Semester.objects.get(current=True)
    courses = Course.objects.filter(group__registration__user=request.user).filter(semester=current_semester)
    
    return render_to_response('courses/course_list.html', locals(), context_instance=RequestContext(request))

@login_required
def course_details(request, course_slug):
    course = Course.objects.get(slug=course_slug)
    course_groups = Group.objects.filter(course=course)
    
    return render_to_response('courses/course_details.html', locals(), context_instance=RequestContext(request))

@login_required
def group_details(request, course_slug, group_slug):
    course = Course.objects.get(slug=course_slug)
    if course:
        group = Group.objects.get(slug=group_slug, course=course)
        if not group:
            messages.add_message(request, messages.ERROR, _("The group does not exist."))
    else:
        messages.add_message(request, messages.ERROR, _("The course does not exist."))
    
    return render_to_response('courses/group_details.html', locals(), context_instance=RequestContext(request))
    
@login_required
def create_preferences(request, course_slug):    
    course = Course.objects.get(slug=course_slug)
    groups = Group.objects.filter(course=course)
    number_of_preferences = min(len(groups), Preference.max_preferences) # the minimum of the group count and the number of allowed preferences in the model
    
    group_choices = [(g.id, g.name) for g in groups]
    
    class PreferenceForm(forms.Form):
        preference = forms.ChoiceField(choices=group_choices, label=_("preference"))
    
    PrefereceFormSet = formset_factory(PreferenceForm, max_num=number_of_preferences, extra=number_of_preferences, formset=BasePreferenceFormSet)
    
    if request.method == 'POST':    # form was submitted
        formset = PrefereceFormSet(request.POST)
        
        if formset.is_valid():
            # create mapping with user, group and preference from POST data
            pref = 1
            user_group_preference_mapping = []
            
            for form in formset:
                pref_group = form.cleaned_data['preference']
                user_group_preference_mapping.append(
                    (request.user, Group.objects.get(id=pref_group), pref)
                )
                pref += 1
            
            #  delete old preferences and save new ones
            Preference.objects.filter(user=request.user,group__course=course).delete()
            preference_administrator.save_user_preferences_for_groups(user_group_preference_mapping)
            messages.add_message(request, messages.SUCCESS, _("Preferences saved."))
        else:
            # notice: the django 'messages framework' is used. so formset errors have to be converted into correct error messages
            for error_message in formset.non_form_errors():
                messages.add_message(request, messages.ERROR, error_message)
    
    else:   # create form
        formset = PrefereceFormSet()
    
    return render_to_response('courses/create_preferences.html', locals(), context_instance=RequestContext(request))



def register_user_to_group(request, course_slug, group_slug):
    if request.method == 'POST':
        registrator = Registrator()
        group = Group.objects.get(slug=request.POST['register_group_slug'])
        registration,created = registrator.register_user_for_group(request.user, group)
        if created:
            messages.add_message(request, messages.SUCCESS, _("You successfully registered to the group."))
        elif registration:
            messages.add_message(request, messages.ERROR, _("You are already registered to this course."))
        else:
            messages.add_message(request, messages.ERROR, _("You cannot register to this group. The Group is full."))
        
        # go back to the view that called the registration
        default_back_url = "courses/group_details.html"
        back_url = request.META.get('HTTP_REFERER', default_back_url)
        if back_url:
            return HttpResponseRedirect(back_url)
        else:
            return HttpResponseRedirect(default_back_url)

templates/courses/course_details.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}
	{% trans "Course" %}: {{course.name}}
{% endblock %}

{% block body %}
   	<h1>{{course.name}}</h1>
   	
   	<table>
    	<tr>
    		<td>
    			{% trans "Name" %}
    		</td>
    		<td>
    			{{course.name}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Description" %}
    		</td>
    		<td>
    			{{course.description}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "End of Preference Phase" %}
    		</td>
    		<td>
    			{{course.end_of_preference_phase}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Start of Registration Phase" %}
    		</td>
    		<td>
    			{{course.start_of_registration_phase}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Capacity" %}
    		</td>
    		<td>
    			{{course.used_capacity}}/{{course.capacity}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Active" %}
    		</td>
    		<td>
    			{{course.active}}
    		</td>
    	</tr>
   	</table>
   	
   	<a href="/courses/{{course.slug}}/preferences">{% trans "Submit your preferences" %}</a>
   	
   	<h2>Groups</h2>
   	
   	<table>
    		<tr>
    			<th>
    				{% trans "Name" %}
    			</th>
    			<th>
    				{% trans "Capacity" %}
    			</th>
    			<th>
    				{% trans "Register" %}
    			</th>
    		</tr>
    		
    		{% for group in course_groups %}
    		<tr>
		    	<td>
		    		<a href="/courses/{{course.slug}}/{{group.slug}}">
		    			{{group.name}}
		    		</a>
		    	</td>
		    	<td>
		    		{{group.used_capacity}}/{{group.capacity}}
		    	</td>
		    	<td>
		    		{% if user.is_authenticated %}
			    		<form action="/courses/{{course.slug}}/{{group.slug}}/register" method="POST">
				    		{% csrf_token %}
					    	<input id="register_group_slug" type="hidden" name="register_group_slug" value="{{group.slug}}" />
					    	<input type="submit" value="{% trans "Register" %}" />
				    	</form>
				    {% else %}
				    	{% trans "Login required" %}
			    	{% endif %}
		    	</td>
    		</tr>
   			{% endfor %}
   	</table>
{% endblock %}

templates/courses/course_list.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}
	{{site_headline}}
{% endblock %}

{% block body %}
   	<h1>{{site_headline}}</h1>
   	
   	<table>
   		<tr>
   			<th>
   				{% trans "Name" %}
   			</th>
   			<th>
   				{% trans "Active" %}
   			</th>
   		</tr>
    	{% for course in courses %}
   		<tr>
   			<td>
   				<a href="/courses/{{course.slug}}">
   					{{course.name}}
   				</a>
   			</td>
   			<td>
   				{{course.active}}
   			</td>
   		</tr>
    	{% endfor %}
   	</table>
{% endblock %}

templates/courses/create_preferences.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}
	{% trans "Course" %}: {{group.course.name}}: {% trans "Preferences" %}
{% endblock %}

{% block body %}
   	<h1>{% trans "Create Preferences" %}: {{course.name}}</h1>
   	
   	<p>
   		{% trans "Notice that existing preferences will be deleted." %}
   	</p>
   	
   	<form action="/courses/{{course.slug}}/preferences/" method="POST">

   		{% csrf_token %}
   		{{ formset.management_form }}
   		{% for form in formset %}
   			{{ forloop.counter }}. {{ form }}</br>
   		{% endfor %}
   		<br/>
    	<input type="submit" value="{% trans "Submit Preferences" %}" />
   	</form>
{% endblock %}

templates/courses/group_details.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}
	{% trans "Course" %}: {{group.course.name}}, {% trans "Group" %}: {{group.name}}
{% endblock %}

{% block body %}
   	<h1>{{group.name}}</h1>
   	
   	<table>
    	<tr>
    		<td>
    			{% trans "Group Name" %}
    		</td>
    		<td>
    			{{group.name}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Course" %}
    		</td>
    		<td>
    			{{group.course.name}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Description" %}
    		</td>
    		<td>
    			{{group.description}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Capacity" %}
    		</td>
    		<td>
    			{{group.used_capacity}}/{{group.capacity}}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Rhythm" %}
    		</td>
    		<td>
    			{{ group.get_rhythm_display }}
    		</td>
    	</tr>
    	<tr>
    		<td>
    			{% trans "Place" %}
    		</td>
    		<td>
    			{{group.place}}
    		</td>
    	</tr>
   	</table>
   	
   	{% if user.is_authenticated %}
    	<form action="/courses/{{course.slug}}/{{group.slug}}/register" method="POST">
    		{% csrf_token %}
	    	<input id="register_group_slug" type="hidden" name="register_group_slug" value="{{group.slug}}" />
	    	<input type="submit" value="{% trans "Register" %}" />
    	</form>
   	{% endif %}
  
{% endblock %}